inherit_from: .rubocop_todo.yml

Lint/DuplicateMethods:
  Enabled: false

Metrics/AbcSize:
  Max: 21

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/LineLength:
  Max: 160