version: '3'

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - tmp-volume:/app/tmp
      - '~/.ssh:/root/.ssh'
    tty: true
    stdin_open: true

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - tmp-volume:/app/tmp
    depends_on:
      - app

volumes:
  tmp-volume: # volumeを使ってsockファイルにアクセス