version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle config set path 'vendor/bundle' && \
             bundle install -j4
      - run: apt-get update && apt-get install -y yarn && \
             yarn upgrade && \
             rails webpacker:install && \
             yarn install --check-files